name: Convert DOCX to PDF

on:
  push:
    paths:
      - '*.docx'

jobs:
  convert-docx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LibreOffice
      run: sudo apt-get update && sudo apt-get install -y libreoffice

    - name: Convert DOCX to PDF
      run: |
        mkdir -p pdf_output
        for docx_file in *.docx; do
          filename=$(basename "$docx_file" .docx)
          libreoffice --headless --convert-to pdf "$docx_file" --outdir pdf_output
        done

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Converted PDFs
        path: pdf_output/
