name: Reminder to Convert DOCX to PDF

on:
  push:
    paths:
      - '*.docx'

jobs:
  notify-docx-push:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy notification step
        run: echo "A DOCX file was pushed. This is a dummy workflow for notification purposes."
